apiVersion: v2
name: plumber-platform
description: Helm chart for the Plumber Platform (v2 line). The v1 chart is `plumber`.
type: application
version: "2.5.1"
appVersion: "2.5.1"
home: https://github.com/getplumber/plumber-platform/
sources:
  - https://github.com/getplumber/plumber-platform
keywords:
  - plumber
  - ci-cd
  - security
  - compliance
maintainers:
  - name: devpro
    email: bertrand@devpro.fr
  - name: gemini-jtff
    email: slongo@klanik.com
  - name: thomasboni
    email: thomas@getplumber.io
  - name: Totara-thib
    email: thibaud@getplumber.io
  - name: Joseph94m
    email: joseph.moukarzel@jmclarity.com
